name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5115eb7053f056cf6fc599c95dcd2dcb4af7f42946b2a09b8f3a9bb4b7b905f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
