name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15f218cf1b0eb16f363d0ea68b3779f8623ffc613660fa20b41b797c55fc5341"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
