name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a2add0748fd27e37c8a1883ba7f4262f01954934204ad15af92837bac6d2fb7"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
