name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "573c93bb16eec32ed22a29ef205e8c114a1af575b1536774824b4cbb0ff14d62"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
