name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9f39a3a7b2849196ddcba27a68d223d32e62814b665851fd956fd2925fa297a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
