name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34f3e3e89618dc7ac83fdc43f7f9111830f88e571df589464d15308f0d740d1e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
