name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad423ecaa50053d1029ab66ac1842f11c652f5b7aa59b2b12384d694ea749c4"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
