name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ed982986483d2a0ab6d774f0fed58ce70ca14e89b86dc3e778b0594b0245c62"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
