name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c1667cad8853d008fe54090d36e9c58353d7f6b0d31736d5dd9d9e60e77fce1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
