name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf8685fa290a0bea334fccd69c1f92e0854d6d2df490538f238d471ce9f3b896"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
