name = "Minceraft"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb67a43cadd0343e2e84fb4b45ccdb90b9ff01d7e79b21c9029c0df48c74f065"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
