name = "Minceraft"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d488bb191aae68d3161cd08ab70f5050da8204aa765c82d4beb01baa529cb89"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
