name = "Minceraft"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da30fd8b7658d867c5dc2ce5691cbf98d3c6f8b90310df660bd6ae30299ce5a9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
