name = "Minceraft"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a8dedb9cc0eb9903314ea3e46fd3f1749fc7584b5c9f2d2557a251f56af971f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
